name: Sync dev branch with main

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:
  sync-dev-branch:
    runs-on: windows-latest  # 或 windows-11-arm 以支持Arm架构

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 升级到v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "gitHub-actions"
          git config --global user.email "action@github.com"
        shell: pwsh

      - name: Rebase dev onto main
        run: |
          git fetch origin main dev
          git checkout dev
          git rebase origin/main
        shell: pwsh

      - name: Push dev branch
        run: |
          git push origin dev --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
