name: Build and draft a release

on: workflow_dispatch

jobs:
  build_and_draft_release:
    env:
      BUILD_PATH: ${{ github.workspace }}\build\neo-bpsys-wpf
      PROJ_PATH: ${{ github.workspace }}\neo-bpsys-wpf\neo-bpsys-wpf.csproj
      INSTALLER_GENERATE_DIR: ${{ github.workspace }}\InstallerGenerate
      INSTALLER_OUTPUT: ${{ github.workspace }}/build/neo-bpsys-wpf_Installer.exe
      VERSION:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
      
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: |
        New-Item -Path ${{ github.workspace }}\build -ItemType Directory -Force
        dotnet publish ${{ env.PROJ_PATH }} -c Release -o ${{ env.BUILD_PATH }}

    - name: Pack Installer
      shell: cmd
      run : |
        "${{ env.INSTALLER_GENERATE_DIR }}\Inno Setup 6\ISCC.exe" "${{ env.INSTALLER_GENERATE_DIR }}\build_Installer.iss"

    - name: Get Version
      shell: pwsh
      run : |
        $file = "${{ env.INSTALLER_OUTPUT }}"
        $version = (Get-Item $file).VersionInfo.ProductVersion
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Draft Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        tag_name: v${{ env.VERSION }}
        files: ${{ env.INSTALLER_OUTPUT }}
        name: Release-v${{ env.VERSION }}